# Application Configuration
server:
  port: 8081

spring:
  application:
    name: winsu

  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/winsu
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate # Use 'validate' to ensure the schema matches the entities
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: liquibase/master.xml

  # Security Configuration (for Google Sign-In)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.liquibase: INFO
  file:
    name: logs/quizapp.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom Application Properties
app:
  reward:
    daily-distribution-time: "23:59" # Time to distribute rewards daily